//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Zakazs = new HashSet<Zakaz>();
        }
    
        public int IdCar { get; set; }
        public int DerzhNomer { get; set; }
        public string Color { get; set; }
        public int ProdYear { get; set; }
        public int IdKlient { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual ICollection<Zakaz> Zakazs { get; set; }
    }
}
