//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public Master()
        {
            this.Zakazs = new HashSet<Zakaz>();
        }
    
        public int IdMaster { get; set; }
        public string Name { get; set; }
        public Nullable<int> Salary { get; set; }
    
        public virtual ICollection<Zakaz> Zakazs { get; set; }
    }
}
