//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int IdZakaz { get; set; }
        public int IdCar { get; set; }
        public int IdAdmin { get; set; }
        public int IdMaster { get; set; }
        public int IdKlient { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Car Car { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Master Master { get; set; }
    }
}
